name: Deploy to Cloud Run
on:
  push:
    branches: main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: vvgo
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/131369498938/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "vvgo-cloud-run@discordbot-366303.iam.gserviceaccount.com"

      # Alternative option - authentication via credentials json
      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest .
          docker push asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest \
            --platform "managed" \
            --quiet
